vacuum_clean_zone:
  name: Vacuum clean zone
  description: Start the cleaning operation in the selected areas for the number of repeats indicated.
  target:
    entity:
      integration: roborock
      domain: vacuum
  fields:
    zone:
      name: Zone
      description: Array of zones. Each zone is an array of 4 integer values.
      required: true
      example: "[[23510,25311,25110,26362]]"
      selector:
        object:
    repeats:
      name: Repeats
      description: Number of cleaning repeats for each zone.
      selector:
        number:
          min: 1
          max: 3

vacuum_clean_segment:
  name: Vacuum clean segment
  description: Start cleaning of the specified segment(s).
  target:
    entity:
      integration: roborock
      domain: vacuum
  fields:
    segments:
      name: Segments
      description: Segments.
      required: true
      example: "[1,2]"
      selector:
        object:

vacuum_set_mop_mode:
  name: Vacuum set mop mode
  description: Change vacuum mop mode.
  target:
    entity:
      integration: roborock
      domain: vacuum
  fields:
    mop_mode:
      name: Mop Mode
      description: Mop mode.
      required: true
      example: "standard"
      selector:
        select:
          options:
            - "standard"
            - "deep"
            - "deep_plus"
            - "custom"

vacuum_set_mop_intensity:
  name: Vacuum set mop intensity
  description: Change vacuum mop intensity.
  target:
    entity:
      integration: roborock
      domain: vacuum
  fields:
    mop_intensity:
      name: Mop Intensity
      description: Mop intensity.
      required: true
      example: "mild"
      selector:
        select:
          options:
            - "off"
            - "mild"
            - "moderate"
            - "intense"
            - "custom"

vacuum_set_fan_speed:
  name: Vacuum set fan speed
  description: Change vacuum fan speed.
  target:
    entity:
      integration: roborock
      domain: vacuum
  fields:
    fan_speed:
      name: Fan speed
      description: Fan speed.
      required: true
      example: "balanced"
      selector:
        select:
          options:
            - "off"
            - "silent"
            - "balanced"
            - "turbo"
            - "max"
            - "max_plus"
            - "custom"

vacuum_reset_consumables:
  name: Vacuum reset consumables
  description: Reset vacuum consumables.
  target:
    entity:
      integration: roborock
      domain: vacuum
